### ISSUE TITLE
Stale DAPI Sessions causing issues

### ISSUE THREAD

**Issue by havi-b** [Luidog/fms-api-client#66]
**Describe the bug**
I took your advice and set up my service to store the client objects in MongoDB and I'm retrieving it by the '_id' which is sent to the client in a JWT token.

The service seems to run fine while the initial DAPI session(s) are active. However, if a session is disconnected, either automatically after the set 15 minutes or manually from the FileMaker admin console, I completely lose the ability to make any requests (finds, edits, deletes, etc.). After some debugging I found that the client.request methods isn't returning a promise causing neither the .then nor .catch blocks execute.

Sometimes the initial request will fail and subsequent requests will work, however a new session is created and that is what is used. Up to 4 new sessions are created even though my concurrency is set to 2.

**Expected behavior**
Stale/disconnected DAPI sessions should be removed and a new session should be created and used for subsequent requests.

**Additional context**
Concurrency is set to 2.

A client object retrieved from MongoDB:
* This was the state of the client object after the session had already expired.
* Some information removed for security.
```
{
	"_id" : ObjectId("5e696c3d3927e5281f71e0b9"),
	"name" : "2020-03-11 22:54:53",
	"data" : {
		"track" : false,
		"in" : 0,
		"out" : 0,
		"since" : "2020-03-11T17:54:53-05:00"
	},
	"agent" : {
		"global" : "REMOVED",
		"protocol" : "https",
		"agent" : null,
		"connection" : {
			"server" : "REMOVED",
			"database" : "REMOVED",
			"version" : "vLatest",
			"starting" : true,
			"sessions" : [
				{
					"id" : "b0c87093-e87e-49d7-86b0-0a2f17b0a365",
					"issued" : "2020-03-11T17:54:54-05:00",
					"expires" : "2020-03-11T18:09:54-05:00",
					"used" : "2020-03-11T17:54:54-05:00",
					"active" : true,
					"token" : "REMOVED",
					"url" : "REMOVED"
				}
			],
			"credentials" : {
				"password" : "REMOVED",
				"user" : "REMOVED"
			}
		},
		"concurrency" : 2,
		"queue" : [ ],
		"pending" : [ ],
		"timeout" : 120000,
		"delay" : 1,
		"proxy" : null
	}
}
```

**Comment by Luidog** [comment]
Thank you for the information @havi-b. I will look into it. 

I am also open to a PR if you want to take a pass at fixing it.

**Comment by havi-b** [comment]
After working with @Luidog to debug this issue, it turns out there was a known session collision issue on the FM Server side. The version of FM Server I was using still had the session collision issue, however after I  upgraded the FM Server to 18.0.3 the issue was resolved and everything has been working smoothly! 😄
