### ISSUE TITLE
Sessions aren't reused

### ISSUE THREAD

**Issue by mfrro** [Luidog/fms-api-client#71]
**Describe the bug**
Sessions aren't reused, there is a new session created for every request. 
This can be reproduced with the code in the example section, where I'm calling a find request every 5 seconds. 
The newly created sessions can be observed in the admin-console. 
With a few active clients, the number of sessions climbs very quickly. 
http://127.0.0.1:16001/admin-console/app/activities

**Expected behavior**
A session should be set to inactive once it receives a response or an error, so it can be reused for the next request. 

**Code Examples**
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

const { Filemaker } = require('fms-api-client')

// datastore-connect for fms-api-client
const { connect } = require('marpat')

const config = {
    server: 'https://SERVER',
    user: 'USER',
    password: 'PASS',
    db: 'DB',
    layout: 'LAYOUT',
    value: 'VALUE'
}

test()

async function test() {
    try {

        await connect('nedb://memory')

        const client = Filemaker.create({
            database: config.db,
            server: config.server,
            user: config.user,
            password: config.password,
            concurrency: 25,
            timeout: 10000,
        })
        await client.save()

        await findInterval(client)
    } catch (error) {
        console.log(error)
    }
}

async function findInterval(client) {
    const response = await client.find(config.layout, [{ id: config.value }])
    console.log(response)
    setTimeout(() => {
        findInterval(client)
    }, 5000)
}`

**Additional context**
Happens on Filemaker Server 18.0.3, aswell as 18.0.4. 

I've identified 2 issues and created a fix in this fork, which seems to work so far. 
As I'm not familiar with the project, I might've overlooked something. What do think of it? 
https://github.com/radiorottu/fms-api-client/commit/f68a77c2054484d16956b09702fc99144dce7c58

**Comment by Luidog** [comment]
Thank you for your interest and for the commits to the project @mfrro. I took a look at your changes and saw some good work. It would be great to see a PR so that the changes can be run against the suite of tests.

**Comment by Luidog** [comment]
Thank you for pointing out that sessions were not being properly set to inactive @mfrro. I took your suggestions. and added a deactivate method to the connection model and the session model.

It turns out that there are times where the previous request's config is not present when handleError method. The agent's watch method will now check for these sessions in this state during its recursive method.
